<?php
declare(strict_types=1);

namespace Tests\TestCase\View\Helpers\Form\Context\Postgres;

use Fyre\Form\Rule;
use PHPUnit\Framework\Attributes\DataProvider;

trait BigIntTestTrait
{
    /**
     * @return array<string, array{string, string}>
     */
    public static function bigIntLowerValidationBoundProvider(): array
    {
        return [
            'inclusive' => [
                'greaterThanOrEquals',
                '<input id="value" name="value" type="number" placeholder="Value" min="100" step="1" />',
            ],
            'exclusive' => [
                'greaterThan',
                '<input id="value" name="value" type="number" placeholder="Value" min="101" step="1" />',
            ],
        ];
    }

    /**
     * @return array<string, array{string, string}>
     */
    public static function bigIntUpperValidationBoundProvider(): array
    {
        return [
            'inclusive' => [
                'lessThanOrEquals',
                '<input id="value" name="value" type="number" placeholder="Value" max="1000" step="1" />',
            ],
            'exclusive' => ['lessThan', '<input id="value" name="value" type="number" placeholder="Value" max="999" step="1" />'],
        ];
    }

    public function testBigIntBetweenValidation(): void
    {
        $this->db->query(<<<'SQL'
            CREATE TABLE contexts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value BIGINT NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->validator->add('value', Rule::between(100, 1000));

        $entity = $this->model->newEmptyEntity();

        $this->view->Form->open($entity);

        $this->assertSame(
            '<input id="value" name="value" type="number" placeholder="Value" min="100" max="1000" step="1" />',
            $this->view->Form->input('value')
        );
    }

    public function testBigIntEntityValue(): void
    {
        $this->db->query(<<<'SQL'
            CREATE TABLE contexts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value BIGINT NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $entity = $this->model->newEntity([
            'value' => 999,
        ]);

        $this->view->Form->open($entity);

        $this->assertSame(
            '<input id="value" name="value" type="number" value="999" placeholder="Value" step="1" />',
            $this->view->Form->input('value')
        );
    }

    #[DataProvider('bigIntLowerValidationBoundProvider')]
    public function testBigIntLowerValidationBound(string $rule, string $expected): void
    {
        $this->db->query(<<<'SQL'
            CREATE TABLE contexts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value BIGINT NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->validator->add('value', Rule::$rule(100));

        $entity = $this->model->newEmptyEntity();

        $this->view->Form->open($entity);

        $this->assertSame(
            $expected,
            $this->view->Form->input('value')
        );
    }

    public function testBigIntMinMaxSchema(): void
    {
        $this->db->query(<<<'SQL'
            CREATE TABLE contexts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value BIGINT NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $entity = $this->model->newEmptyEntity();

        $this->view->Form->open($entity);

        $this->assertSame(
            '<input id="value" name="value" type="number" placeholder="Value" step="1" />',
            $this->view->Form->input('value')
        );
    }

    public function testBigIntRequiredValidation(): void
    {
        $this->db->query(<<<'SQL'
            CREATE TABLE contexts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value BIGINT NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->validator->add('value', Rule::required());

        $entity = $this->model->newEmptyEntity();

        $this->view->Form->open($entity);

        $this->assertSame(
            '<input id="value" name="value" type="number" placeholder="Value" step="1" required />',
            $this->view->Form->input('value')
        );
    }

    public function testBigIntSchemaDefaultValue(): void
    {
        $this->db->query(<<<'SQL'
            CREATE TABLE contexts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value BIGINT NOT NULL DEFAULT 999,
                PRIMARY KEY (id)
            )
        SQL);

        $entity = $this->model->newEmptyEntity();

        $this->view->Form->open($entity);

        $this->assertSame(
            '<input id="value" name="value" type="number" value="999" placeholder="Value" step="1" />',
            $this->view->Form->input('value')
        );
    }

    #[DataProvider('bigIntUpperValidationBoundProvider')]
    public function testBigIntUpperValidationBound(string $rule, string $expected): void
    {
        $this->db->query(<<<'SQL'
            CREATE TABLE contexts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value BIGINT NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->validator->add('value', Rule::$rule(1000));

        $entity = $this->model->newEmptyEntity();

        $this->view->Form->open($entity);

        $this->assertSame(
            $expected,
            $this->view->Form->input('value')
        );
    }
}
