<?php
declare(strict_types=1);

namespace Tests\TestCase\DB\Schema\Postgres;

use Fyre\Cache\CacheManager;
use Fyre\Cache\Handlers\File\FileCacher;
use Fyre\Core\Config;
use Fyre\Core\Container;
use Fyre\DB\Connection;
use Fyre\DB\ConnectionManager;
use Fyre\DB\Handlers\Postgres\PostgresConnection;
use Fyre\DB\Schema\SchemaRegistry;
use Fyre\DB\TypeParser;
use Tests\TestCase\DB\Schema\Shared\ConnectionTrait;

use function getenv;

trait PostgresConnectionTrait
{
    use ConnectionTrait;

    protected static function buildContainer(): Container
    {
        $container = new Container();
        $container->singleton(TypeParser::class);
        $container->singleton(Config::class);
        $container->singleton(CacheManager::class);
        $container->singleton(ConnectionManager::class);
        $container->singleton(SchemaRegistry::class);
        $container->use(CacheManager::class)->setConfig('_schema', [
            'className' => FileCacher::class,
            'path' => 'tmp',
            'prefix' => 'schema.',
            'expire' => 3600,
        ]);
        $container->use(Config::class)->set('Database', [
            'default' => [
                'className' => PostgresConnection::class,
                'host' => getenv('POSTGRES_HOST'),
                'username' => getenv('POSTGRES_USERNAME'),
                'password' => getenv('POSTGRES_PASSWORD'),
                'database' => getenv('POSTGRES_DATABASE'),
                'port' => getenv('POSTGRES_PORT'),
                'charset' => 'utf8',
                'persist' => true,
            ],
        ]);

        return $container;
    }

    protected static function createSchema(Connection $db): void
    {
        $db->query(<<<'SQL'
            CREATE TABLE test (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                name CHARACTER VARYING(255) NULL DEFAULT NULL,
                value INTEGER NOT NULL DEFAULT 5,
                price NUMERIC(10,2) NOT NULL DEFAULT 2.50,
                text CHARACTER VARYING(255) NOT NULL DEFAULT 'default',
                bool BOOLEAN NOT NULL DEFAULT FALSE,
                date_precision TIMESTAMP(0) NULL DEFAULT NULL,
                created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                modified TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id)
            )
        SQL);
        $db->query(<<<'SQL'
            CREATE UNIQUE INDEX name ON test (name)
        SQL);
        $db->query(<<<'SQL'
            CREATE INDEX name_value ON test (name, value)
        SQL);
        $db->query(<<<'SQL'
            CREATE TABLE test_values (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                test_id INTEGER NOT NULL DEFAULT '0',
                value INTEGER NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $db->query(<<<'SQL'
            CREATE INDEX test_values_test_id ON test_values (test_id)
        SQL);
        $db->query(<<<'SQL'
            CREATE INDEX value ON test_values (value)
        SQL);
        $db->query(<<<'SQL'
            ALTER TABLE test_values ADD CONSTRAINT test_values_test_id FOREIGN KEY (test_id) REFERENCES public.test (id) ON UPDATE CASCADE ON DELETE CASCADE
        SQL);
    }
}
