<?php
declare(strict_types=1);

namespace Fyre\Utility;

use Fyre\Core\Traits\DebugTrait;
use Fyre\Core\Traits\MacroTrait;
use Fyre\Core\Traits\StaticMacroTrait;
use InvalidArgumentException;
use RuntimeException;

use function base64_encode;
use function escapeshellarg;
use function fclose;
use function file_exists;
use function file_get_contents;
use function shell_exec;
use function sprintf;
use function stream_get_meta_data;
use function tmpfile;
use function unlink;

/**
 * Provides PDF generation utilities.
 *
 * PDFs are generated by invoking a headless Chrome/Chromium binary. The binary path and timeout are configurable.
 */
class Pdf
{
    use DebugTrait;
    use MacroTrait;
    use StaticMacroTrait;

    protected static string $binaryPath = 'google-chrome';

    protected static int $timeout = 5000;

    /**
     * Generates a Pdf from a HTML string.
     *
     * @param string $html The HTML string.
     * @return static The new Pdf instance.
     */
    public static function createFromHtml(string $html): static
    {
        $base64 = base64_encode($html);

        return new static('data:text/html;base64,'.$base64);
    }

    /**
     * Generates a Pdf from a URL or file path.
     *
     * @param string $url The URL or file path.
     * @return static The new Pdf instance.
     */
    public static function createFromUrl(string $url): static
    {
        return new static($url);
    }

    /**
     * Returns the Chrome binary path.
     *
     * @return string The Chrome binary path.
     */
    public static function getBinaryPath(): string
    {
        return static::$binaryPath;
    }

    /**
     * Returns the timeout in milliseconds.
     *
     * @return int The timeout in milliseconds.
     */
    public static function getTimeout(): int
    {
        return static::$timeout;
    }

    /**
     * Sets the Chrome binary path.
     *
     * @param string $binaryPath The Chrome binary path.
     */
    public static function setBinaryPath(string $binaryPath): void
    {
        static::$binaryPath = $binaryPath;
    }

    /**
     * Sets the timeout in milliseconds.
     *
     * @param int $timeout The timeout in milliseconds.
     */
    public static function setTimeout(int $timeout): void
    {
        static::$timeout = $timeout;
    }

    /**
     * Constructs a Pdf.
     *
     * @param string $source The source.
     */
    public function __construct(
        protected string $source
    ) {}

    /**
     * Saves the Pdf as a file.
     *
     * Note: This method invokes an external binary and writes the resulting PDF to disk.
     *
     * @param string $filePath The file path.
     *
     * @throws InvalidArgumentException If the file path is empty.
     * @throws RuntimeException If the file already exists, or the PDF could not be generated.
     */
    public function save(string $filePath): void
    {
        if (!$filePath) {
            throw new InvalidArgumentException('File path is required.');
        }

        if (file_exists($filePath)) {
            throw new RuntimeException(sprintf(
                'File `%s` already exists.',
                $filePath
            ));
        }

        $command = sprintf(
            '%s --headless --deterministic-mode --print-to-pdf=%s --no-pdf-header-footer --timeout=%d %s',
            escapeshellarg(static::$binaryPath),
            escapeshellarg($filePath),
            static::$timeout,
            escapeshellarg($this->source)
        );

        shell_exec($command.' 2>&1');

        if (!file_exists($filePath)) {
            throw new RuntimeException(sprintf(
                'PDF file `%s` could not be generated.',
                $filePath
            ));
        }
    }

    /**
     * Returns the binary data.
     *
     * @return string The binary data.
     *
     * Note: This method generates the PDF to a temporary file and returns the file contents.
     *
     * @throws RuntimeException If the PDF could not be generated or read.
     */
    public function toBinary(): string
    {
        $tmpFile = tmpfile();

        if ($tmpFile === false) {
            throw new RuntimeException('Unable to create temporary file for PDF generation.');
        }

        $metaData = stream_get_meta_data($tmpFile);
        fclose($tmpFile);

        if (!isset($metaData['uri'])) {
            throw new RuntimeException('Temporary file path is not available.');
        }

        $path = $metaData['uri'];

        try {
            $this->save($path);

            $output = file_get_contents($path);

            if ($output === false) {
                throw new RuntimeException(sprintf(
                    'PDF file `%s` could not be read.',
                    $path
                ));
            }
        } finally {
            @unlink($path);
        }

        return $output;
    }
}
