<?php
declare(strict_types=1);

namespace Fyre\Utility;

use Fyre\Core\Traits\DebugTrait;
use Fyre\Core\Traits\MacroTrait;
use Fyre\Core\Traits\StaticMacroTrait;
use InvalidArgumentException;
use RuntimeException;

use function array_replace;
use function base64_encode;
use function escapeshellarg;
use function fclose;
use function file_exists;
use function file_get_contents;
use function shell_exec;
use function sprintf;
use function stream_get_meta_data;
use function tmpfile;
use function unlink;

/**
 * Provides PDF generation utilities.
 *
 * PDFs are generated by invoking a configurable headless Chrome/Chromium binary.
 *
 * @phpstan-consistent-constructor
 */
class Pdf
{
    use DebugTrait;
    use MacroTrait;
    use StaticMacroTrait;

    /**
     * @var array{binaryPath: string, timeout: int}
     */
    protected static array $defaults = [
        'binaryPath' => 'google-chrome',
        'timeout' => 5000,
    ];

    protected string $binaryPath;

    protected int $timeout;

    /**
     * Generates a Pdf from a HTML string.
     *
     * @param string $html The HTML string.
     * @param array{binaryPath?: string, timeout?: int} $options The Pdf options.
     * @return static The new Pdf instance.
     */
    public static function createFromHtml(string $html, array $options = []): static
    {
        $base64 = base64_encode($html);

        return new static('data:text/html;base64,'.$base64, $options);
    }

    /**
     * Generates a Pdf from a URL or file path.
     *
     * @param string $url The URL or file path.
     * @param array{binaryPath?: string, timeout?: int} $options The Pdf options.
     * @return static The new Pdf instance.
     */
    public static function createFromUrl(string $url, array $options = []): static
    {
        return new static($url, $options);
    }

    /**
     * Constructs a Pdf.
     *
     * @param string $source The source.
     * @param array{binaryPath?: string, timeout?: int} $options The Pdf options.
     *
     * @throws InvalidArgumentException If the Pdf options are not valid.
     */
    public function __construct(
        protected string $source,
        array $options = []
    ) {
        $options = array_replace(static::$defaults, $options);

        $this->binaryPath = $options['binaryPath'];
        $this->timeout = $options['timeout'];

        if ($this->timeout < 0) {
            throw new InvalidArgumentException('PDF option `timeout` must not be negative.');
        }
    }

    /**
     * Returns the Chrome binary path.
     *
     * @return string The Chrome binary path.
     */
    public function getBinaryPath(): string
    {
        return $this->binaryPath;
    }

    /**
     * Returns the timeout in milliseconds.
     *
     * @return int The timeout in milliseconds.
     */
    public function getTimeout(): int
    {
        return $this->timeout;
    }

    /**
     * Saves the Pdf as a file.
     *
     * Note: This method invokes an external binary and writes the resulting PDF to disk.
     *
     * @param string $filePath The file path.
     *
     * @throws InvalidArgumentException If the file path is empty.
     * @throws RuntimeException If the file already exists, or the PDF could not be generated.
     */
    public function save(string $filePath): void
    {
        if (!$filePath) {
            throw new InvalidArgumentException('File path is required.');
        }

        if (file_exists($filePath)) {
            throw new RuntimeException(sprintf(
                'File `%s` already exists.',
                $filePath
            ));
        }

        $command = sprintf(
            '%s --headless --deterministic-mode --print-to-pdf=%s --no-pdf-header-footer --timeout=%d %s',
            escapeshellarg($this->binaryPath),
            escapeshellarg($filePath),
            $this->timeout,
            escapeshellarg($this->source)
        );

        shell_exec($command.' 2>&1');

        if (!file_exists($filePath)) {
            throw new RuntimeException(sprintf(
                'PDF file `%s` could not be generated.',
                $filePath
            ));
        }
    }

    /**
     * Returns the binary data.
     *
     * @return string The binary data.
     *
     * Note: This method generates the PDF to a temporary file and returns the file contents.
     *
     * @throws RuntimeException If the PDF could not be generated or read.
     */
    public function toBinary(): string
    {
        $tmpFile = tmpfile();

        if ($tmpFile === false) {
            throw new RuntimeException('Unable to create temporary file for PDF generation.');
        }

        $metaData = stream_get_meta_data($tmpFile);
        fclose($tmpFile);

        if (!isset($metaData['uri'])) {
            throw new RuntimeException('Temporary file path is not available.');
        }

        $path = $metaData['uri'];

        try {
            $this->save($path);

            $output = file_get_contents($path);

            if ($output === false) {
                throw new RuntimeException(sprintf(
                    'PDF file `%s` could not be read.',
                    $path
                ));
            }
        } finally {
            @unlink($path);
        }

        return $output;
    }
}
